import { ContentWrapper } from "../../../components/ContentWrapper/ContentWrapper";
import { MainContainer } from "../../../components/MainContainer/MainContainer";

function messenger() {
    return (
        <MainContainer keywords="messenger, messages, message, send message">
            <ContentWrapper style="white">
                <div className='px-[25px] py-[30px]'>
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                    MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER MESSENGER
                </div>
            </ContentWrapper>
        </MainContainer>
    )
}
export default messenger;