import React from 'react'
import { ContentWrapper } from '../../../../components/ContentWrapper/ContentWrapper'
import { MainContainer } from '../../../../components/MainContainer/MainContainer'

export default function listTasks() {
    return (
        <MainContainer keywords="tasks, list task, list, list tasks">
            <ContentWrapper style="white">
                <div className='px-[25px] py-[30px]'>
                    LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS
                    LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS
                    LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS
                    LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS
                    LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS
                    LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS
                    LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS
                    LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS
                    LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS
                    LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS
                    LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS
                    LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS
                    LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS
                    LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS LIST-TASKS
                </div>
            </ContentWrapper>
        </MainContainer>
    )
}
