import React from 'react'
import { ContentWrapper } from '../../../../components/ContentWrapper/ContentWrapper'
import { MainContainer } from '../../../../components/MainContainer/MainContainer'

export default function gantt() {
    return (
        <MainContainer keywords="gantt" title={'Gantt'}>
            <ContentWrapper style="white">
                <div className='px-[25px] py-[30px]'>
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                    GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT GANTT
                </div>
            </ContentWrapper>
        </MainContainer>
    )
}
