import { ContentWrapper } from "../../../components/ContentWrapper/ContentWrapper";
import { MainContainer } from "../../../components/MainContainer/MainContainer";

function files() {
    return (
        <MainContainer keywords="FILES, main menu, profile">
            <ContentWrapper style="white">
                <div className='px-[25px] py-[30px]'>
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                    FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES FILES
                </div>
            </ContentWrapper>
        </MainContainer>
    )
}

export default files;