import { ContentWrapper } from "../../../components/ContentWrapper/ContentWrapper";
import { MainContainer } from "../../../components/MainContainer/MainContainer";

function emails() {
    return (
        <MainContainer keywords="EMAILS, main menu, profile">
            <ContentWrapper style="white">
                <div className='px-[25px] py-[30px]'>
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                    EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS EMAILS
                </div>
            </ContentWrapper>
        </MainContainer>
    )
}

export default emails;