import React from 'react'
import { ContentWrapper } from '../../../../components/ContentWrapper/ContentWrapper'
import { MainContainer } from '../../../../components/MainContainer/MainContainer'

export default function boards() {
    return (
        <MainContainer keywords="boards, notes board, board" title={'Boards'}>
            <ContentWrapper style="white">
                <div className='px-[25px] py-[30px]'>
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                    BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS BOARDS
                </div>
            </ContentWrapper>
        </MainContainer>
    )
}
